import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { chromium } from 'playwright';
import { installAccountFixture } from './auth-fixture.mjs';

const origin = process.env.UI_URL ?? 'http://127.0.0.1:4173';
const map = JSON.parse(await readFile('streetcar-schematic.json', 'utf8'));
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 960 } });
  const errors = []; context.on('page', page => page.on('pageerror', error => errors.push(error.message)));
  const { journals } = await installAccountFixture(context);
  await context.route('**/api/v1/map/streetcar?format=schematic-v1', route => route.fulfill({ json: map }));
  await context.route('**/api/v1/vehicles/streetcar', route => route.fulfill({ json: { schemaVersion: 1, fetchedAt: new Date().toISOString(), feedTimestamp: new Date().toISOString(), source: 'auth-test', attribution: 'Fixture', invalidPositions: 0, vehicles: [] } }));
  const page = await context.newPage();
  await page.goto(origin);
  await page.locator('#map').waitFor();
  await page.getByRole('button', { name: 'Sign in', exact: true }).waitFor();
  await page.getByRole('button', { name: 'Sign up', exact: true }).waitFor();
  await page.getByRole('tab', { name: 'Journal', exact: true }).click();
  await page.getByRole('heading', { name: 'Make it your journal.' }).waitFor();
  assert.equal(await page.locator('.journal-entry').count(), 0);
  for (const width of [320, 390, 900, 1440]) {
    await page.setViewportSize({ width, height: 960 });
    assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), `no overflow at ${width}`);
    await page.screenshot({ path: `/tmp/ttc-auth-${width}.png` });
  }
  await page.setViewportSize({ width: 1440, height: 960 });
  await page.getByRole('button', { name: 'Create an account', exact: true }).click();
  await page.getByText('Your journal is saved to your account.', { exact: true }).waitFor();
  await page.evaluate(() => localStorage.setItem('ttc:journal:v1', JSON.stringify([{ vehicleId: '4400', label: '4400', recordedAt: '2026-10-03T12:00:00.000Z', note: 'Private earlier note' }])));
  assert.equal(await page.locator('.journal-entry').count(), 0, 'earlier journal is not imported automatically');
  await page.getByRole('button', { name: 'Import earlier browser journal' }).click();
  await page.getByText('Your journal is saved to your account.', { exact: true }).waitFor();
  assert.equal(await page.locator('.journal-entry').count(), 1);
  assert.equal(journals.get('user_a').entries[0].note, 'Private earlier note');
  await page.evaluate(() => { window.__testUser = 'user_b'; window.dispatchEvent(new Event('fixture-account')); });
  await page.getByText('Your first catch is waiting.', { exact: false }).waitFor();
  assert.equal(await page.locator('.journal-entry').count(), 0, 'switching accounts hides previous entries');
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('heading', { name: 'Make it your journal.' }).waitFor();
  await page.getByRole('button', { name: 'Sign in', exact: true }).first().click();
  await page.getByText('Your journal is saved to your account.', { exact: true }).waitFor();
  assert.equal(await page.locator('.journal-entry').count(), 1);
  await page.getByRole('link', { name: 'Profile', exact: true }).click();
  await page.getByLabel('Username', { exact: true }).waitFor();
  assert.equal(await page.getByLabel('Show my profile and earned badges publicly').isChecked(), false);
  await page.getByLabel('Username', { exact: true }).fill('collector');
  await page.getByRole('button', { name: 'Save profile' }).click();
  await page.getByText('Profile saved.', { exact: true }).waitFor();
  assert.equal(await page.getByRole('link', { name: 'View your public badges', exact: false }).count(), 0);
  await page.getByLabel('Show my profile and earned badges publicly').check();
  await page.getByRole('button', { name: 'Save profile' }).click();
  await page.getByRole('link', { name: 'View your public badges', exact: false }).waitFor();
  assert.equal(await page.getByRole('link', { name: 'View your public badges', exact: false }).getAttribute('href'), '/u/collector#badges');
  await page.getByLabel('Show my profile and earned badges publicly').uncheck();
  await page.getByRole('button', { name: 'Save profile' }).click();
  await page.getByText('Profile saved.', { exact: true }).waitFor();
  assert.equal(await page.getByRole('link', { name: 'View your public badges', exact: false }).count(), 0);
  await page.getByRole('button', { name: 'Sign out' }).click();
  await page.getByRole('heading', { name: 'Make it your journal.' }).waitFor();
  assert.equal(await page.getByLabel('Username', { exact: true }).count(), 0);

  await context.route('**/api/v1/profiles/collector', route => route.fulfill({ json: { username: 'collector', badges: [{ name: 'First catch', icon: '✦', description: 'Add your first streetcar.' }] } }));
  await page.goto(origin + '/u/collector#badges');
  await page.getByRole('heading', { name: '@collector', exact: true }).waitFor();
  await page.getByText('First catch', { exact: true }).waitFor();
  assert.ok(!(await page.locator('body').innerText()).includes('Private earlier note'));
  await page.goto(origin + '/u/private#badges');
  await page.getByText('This profile is private or does not exist.', { exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log('Auth UI passed with an isolated Clerk fixture: public map, sign-in/sign-up controls, protected Journal, explicit legacy import, account switching/sign-out, private profile defaults, badge sharing settings, public/private profile views and 320–1440px layouts.');
  await context.close();
} finally { await browser.close(); }
