import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { build } from 'esbuild';
import { chromium } from 'playwright';

const origin = process.env.UI_URL ?? 'http://127.0.0.1:4173';
const map = JSON.parse(await readFile('streetcar-schematic.json', 'utf8'));
const compiled = await build({ stdin: { contents: `export { mapToGps, pointAlongEdge } from './workers/shared/map-projection';`, resolveDir: process.cwd(), loader: 'ts' }, bundle: true, write: false, format: 'esm' });
const { mapToGps, pointAlongEdge } = await import(`data:text/javascript;base64,${Buffer.from(compiled.outputFiles[0].text).toString('base64')}`);
const errors = [], requests = [];
const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 960 } });
  let feedCalls = 0, mapCalls = 0;
  context.on('page', page => page.on('pageerror', error => errors.push(error.message)));
  await context.route('**/api/v1/auth/config', route => route.fulfill({ json: { enabled: false, publishableKey: null } }));
  await context.route('**/api/v1/map/streetcar?format=schematic-v1', route => { mapCalls++; return route.fulfill({ json: map }); });
  await context.route('**/api/v1/vehicles/streetcar', route => {
    feedCalls++;
    const now = new Date().toISOString();
    const vehicles = map.graph.edges.filter(edge => edge.routeIds.length).slice(0,40).map((edge,index) => {
      const gps = mapToGps(pointAlongEdge(edge,edge.lengthMetres/2).point,map.display.geographicTransform);
      return { id: String(4400+index), label: String(4400+index), ...gps, routeId: edge.routeIds[0], observedAt: now, bearing: 90 };
    });
    return route.fulfill({ headers: { 'x-live-update-seconds': '30' }, json: { schemaVersion: 1, source: 'game-fixture', attribution: 'Fixture', fetchedAt: now, feedTimestamp: now, invalidPositions: 0, vehicles } });
  });
  const page = await context.newPage();
  await page.goto(origin + '/xplore');
  const launch = page.getByRole('button', { name: 'Play Streetcar Snake', exact: true });
  await launch.waitFor();
  await page.getByRole('checkbox', { name: 'Show live streetcars' }).uncheck();
  await launch.click();
  const game = page.getByRole('dialog', { name: 'Streetcar Snake' });
  await game.waitFor();
  assert.ok((await game.getByLabel('Route', { exact: true }).locator('option').count()) > 10);
  await game.getByText(/fresh streetcars on the map/).waitFor();
  assert.equal(mapCalls,1,'game reuses the already-loaded map');
  const before = feedCalls;
  await game.getByRole('button', { name: 'Depart', exact: true }).click();
  await page.waitForTimeout(250);
  const initial = await game.locator('[data-snake-head]').getAttribute('transform');
  await page.waitForTimeout(250);
  assert.notEqual(await game.locator('[data-snake-head]').getAttribute('transform'), initial, 'the streetcar moves along the map');
  await page.keyboard.press('ArrowLeft');
  await page.keyboard.press('p');
  await game.getByText('Paused', { exact: true }).waitFor();
  const paused = await game.locator('[data-snake-head]').getAttribute('transform');
  await page.waitForTimeout(200);
  assert.equal(await game.locator('[data-snake-head]').getAttribute('transform'), paused);
  assert.equal(await page.locator('.map-export-dialog').count(), 0, 'P does not open the xplore export flow');
  await game.getByRole('button', { name: 'Resume driving', exact: true }).click();
  await game.getByRole('button', { name: 'Pause', exact: true }).focus();
  await page.keyboard.press('Space');
  await game.getByText('Paused', { exact: true }).waitFor();
  await game.getByRole('button', { name: 'Resume driving', exact: true }).click();
  await page.keyboard.press('ArrowUp');
  await page.screenshot({ path: '/tmp/ttc-snake-desktop.png' });
  assert.equal(feedCalls,before,'game does not create a second poller');
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(),0);
  await launch.click();
  await game.getByLabel('Driving mode', { exact: true }).selectOption('purist');
  await game.getByRole('button', { name: 'Depart', exact: true }).click();
  await page.waitForTimeout(150);
  assert.equal(await game.locator('[data-snake-count]').innerText(),'1');
  assert.equal(await game.locator('[data-snake-speed]').innerText(),'50');
  await page.keyboard.down('ArrowUp'); await page.waitForTimeout(120); await page.keyboard.up('ArrowUp');
  assert.equal(await game.locator('[data-snake-speed]').innerText(),'50');
  await game.getByRole('button', { name: 'Close Streetcar Snake' }).click();
  assert.ok(await launch.evaluate(element => element === document.activeElement), 'closing restores launcher focus');

  const mobileContext = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true });
  await mobileContext.route('**/api/v1/auth/config', route => route.fulfill({ json: { enabled: false } }));
  await mobileContext.route('**/api/v1/map/streetcar?format=schematic-v1', route => route.fulfill({ json: map }));
  await mobileContext.route('**/api/v1/vehicles/streetcar', route => route.fulfill({ json: { schemaVersion: 1, source:'empty-fixture', attribution:'Fixture', fetchedAt: new Date().toISOString(), feedTimestamp: null, invalidPositions:0, vehicles:[] } }));
  const mobile = await mobileContext.newPage();
  mobile.on('pageerror', error => errors.push(error.message));
  await mobile.goto(origin + '/xplore'); await mobile.getByRole('button', { name:'Play Streetcar Snake' }).tap();
  const cockpit = mobile.getByRole('dialog');
  await cockpit.getByRole('button', { name: 'Depart', exact:true }).tap();
  await mobile.waitForTimeout(150);
  assert.ok(await cockpit.getByRole('button', { name:'Hold to brake' }).isVisible());
  assert.ok(await cockpit.getByRole('button', { name:'Hold to accelerate' }).isVisible());
  assert.ok(await mobile.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  const brake = cockpit.getByRole('button', { name:'Hold to brake' });
  await brake.dispatchEvent('pointerdown', { pointerId: 1, pointerType:'touch' });
  await mobile.waitForTimeout(400);
  await brake.dispatchEvent('pointerup', { pointerId: 1, pointerType:'touch' });
  assert.ok(Number(await cockpit.locator('[data-snake-speed]').innerText()) < 180);
  const touch = await mobileContext.newCDPSession(mobile);
  await touch.send('Input.dispatchTouchEvent', { type:'touchStart', touchPoints:[{x:240,y:460,id:1}] });
  await touch.send('Input.dispatchTouchEvent', { type:'touchMove', touchPoints:[{x:150,y:460,id:1}] });
  await touch.send('Input.dispatchTouchEvent', { type:'touchEnd', touchPoints:[] });
  assert.equal(await cockpit.getByRole('button',{name:'← Left',exact:true}).getAttribute('aria-pressed'),'true','single-finger swipe steers');
  assert.equal(await cockpit.getByRole('button',{name:'Following',exact:true}).getAttribute('aria-pressed'),'true','steering does not disable camera following');
  await cockpit.getByRole('button', { name:'Pause', exact:true }).tap();
  const beforePinch=(await cockpit.locator('#snake-map').getAttribute('viewBox')).split(' ').map(Number)[2];
  await touch.send('Input.dispatchTouchEvent', { type:'touchStart', touchPoints:[{x:120,y:580,id:1},{x:250,y:580,id:2}] });
  await touch.send('Input.dispatchTouchEvent', { type:'touchMove', touchPoints:[{x:90,y:580,id:1},{x:280,y:580,id:2}] });
  await touch.send('Input.dispatchTouchEvent', { type:'touchEnd', touchPoints:[] });
  await mobile.waitForTimeout(100);
  const afterPinch=(await cockpit.locator('#snake-map').getAttribute('viewBox')).split(' ').map(Number)[2];
  assert.ok(afterPinch<beforePinch,'two-finger pinch zooms the shared map');
  assert.equal(await cockpit.getByRole('button',{name:'← Left',exact:true}).getAttribute('aria-pressed'),'true','pinch never changes the queued switch');
  await mobile.screenshot({ path: '/tmp/ttc-snake-mobile.png' });
  await cockpit.getByRole('button', { name:'Close Streetcar Snake' }).tap();

  page.on('requestfailed', request => requests.push(request.url()));
  const response = await page.goto(origin + '/snake/v1');
  assert.equal(response.status(),200);
  await page.locator('#startBtn').waitFor();
  assert.equal(new URL(page.url()).pathname,'/snake/v1/');
  assert.ok(await page.locator('#game').isVisible());
  await page.locator('#startBtn').click();
  await page.waitForTimeout(250);
  await page.screenshot({ path:'/tmp/ttc-snake-legacy.png' });
  assert.deepEqual(requests,[]); assert.deepEqual(errors,[]);
  console.log('Snake browser checks passed: shared map/feed, arcade motion, keyboard and pause, purist governor, mobile pedals, focus restoration, playable legacy archive.');
  await context.close(); await mobileContext.close();
} finally { await browser.close(); }
