import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import ts from 'typescript';

const MAP_NAMES = ['streetcar', 'snake', 'ttcstatus'];

const usage = () => {
  console.log(`Publish map artifact tags against the remote production D1.

Usage:
  npm run map:tag -- set --name <streetcar|snake|ttcstatus> --tag <stable|latest|...> [--artifact <id> | --generator-version <v>]
  npm run map:tag -- clear --name <name> --tag <tag>
  npm run map:tag -- list

Examples:
  npm run map:tag -- set --name streetcar --tag stable            # newest streetcar artifact
  npm run map:tag -- set --name streetcar --tag latest --artifact 42
  npm run map:tag -- set --name snake --tag stable --generator-version snake-v1.4.1
  npm run map:tag -- set --name ttcstatus --tag latest            # pin the stable site map
  npm run map:tag -- clear --name streetcar --tag experimental
`);
};

/** Resolve which artifact a tag should point at, then upsert the tag row. */
export async function tagMap(db, { name, tag, artifactId, generatorVersion }) {
  if (!MAP_NAMES.includes(name))
    throw new Error(`Unknown map name '${name}'. Known names: ${MAP_NAMES.join(', ')}.`);
  if (!/^[\w][\w.-]{0,63}$/.test(tag)) throw new Error(`Invalid tag '${tag}'.`);
  let target;
  if (artifactId) {
    target = await db
      .prepare(
        `SELECT id, version_id, name, style, generator_version, active FROM map_artifacts WHERE id = ?`,
      )
      .bind(artifactId)
      .first();
    if (!target) throw new Error(`No map artifact with id ${artifactId}.`);
    if (target.name !== name)
      throw new Error(
        `Artifact ${artifactId} belongs to map '${target.name}', not '${name}'.`,
      );
  } else if (generatorVersion) {
    target = await db
      .prepare(
        `SELECT id, version_id, name, style, generator_version, active FROM map_artifacts
         WHERE name = ? AND generator_version = ? ORDER BY id DESC LIMIT 1`,
      )
      .bind(name, generatorVersion)
      .first();
    if (!target)
      throw new Error(`No '${name}' artifact generated by ${generatorVersion}.`);
  } else {
    target = await db
      .prepare(
        `SELECT id, version_id, name, style, generator_version, active FROM map_artifacts
         WHERE name = ? ORDER BY id DESC LIMIT 1`,
      )
      .bind(name)
      .first();
    if (!target) throw new Error(`No '${name}' artifact exists yet.`);
  }
  await db
    .prepare(
      `INSERT INTO map_tags (name, tag, artifact_id, updated_at)
       VALUES (?, ?, ?, ?)
       ON CONFLICT(name, tag) DO UPDATE SET artifact_id = excluded.artifact_id, updated_at = excluded.updated_at`,
    )
    .bind(name, tag, target.id, new Date().toISOString())
    .run();
  return {
    name,
    tag,
    artifactId: target.id,
    versionId: target.version_id,
    generatorVersion: target.generator_version,
  };
}

export async function clearMapTag(db, name, tag) {
  const result = await db
    .prepare(`DELETE FROM map_tags WHERE name = ? AND tag = ?`)
    .bind(name, tag)
    .first();
  return { name, tag, removed: Boolean(result) };
}

export async function listMapTags(db) {
  const artifacts = await db
    .prepare(
      `SELECT id, name, version_id, style, generator_version, active, created_at
       FROM map_artifacts ORDER BY id DESC LIMIT 50`,
    )
    .all();
  const tags = await db
    .prepare(
      `SELECT t.name, t.tag, t.artifact_id, t.updated_at
       FROM map_tags t ORDER BY t.name, t.tag`,
    )
    .all();
  return {
    artifacts: artifacts.results,
    tags: tags.results,
    knownNames: MAP_NAMES,
  };
}

async function remoteDb() {
  // Use a temporary config with only the remote production D1 binding. Wrangler
  // supplies credentials; no admin token or GTFS fetch is involved.
  const configPath = 'workers/api/wrangler.jsonc';
  const { config, error } = ts.parseConfigFileTextToJson(
    configPath,
    await readFile(configPath, 'utf8'),
  );
  if (error) throw new Error('Unable to read API Wrangler configuration');
  const binding = config.d1_databases.find((binding) => binding.binding === 'DB');
  if (!binding?.database_id) throw new Error('API DB binding is not configured');
  const dir = await mkdtemp(join(tmpdir(), 'ttc-map-tag-'));
  let platform;
  try {
    const file = join(dir, 'wrangler.json');
    await writeFile(
      file,
      JSON.stringify({
        name: 'ttcstatus-map-tag',
        compatibility_date: config.compatibility_date,
        ...(config.account_id ? { account_id: config.account_id } : {}),
        d1_databases: [
          {
            binding: 'DB',
            database_name: binding.database_name,
            database_id: binding.database_id,
            remote: true,
          },
        ],
      }),
    );
    const { getPlatformProxy } = await import('wrangler');
    platform = await getPlatformProxy({
      configPath: file,
      envFiles: [],
      persist: false,
      remoteBindings: true,
    });
    return { db: platform.env.DB, dispose: () => platform.dispose() };
  } catch (cause) {
    await platform?.dispose();
    await rm(dir, { recursive: true, force: true });
    throw cause;
  }
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const args = process.argv.slice(2);
  const flag = (name) => {
    const index = args.indexOf(`--${name}`);
    return index >= 0 ? args[index + 1] : undefined;
  };
  const [command] = args;
  try {
    if (command === 'list') {
      const { db, dispose } = await remoteDb();
      try {
        console.log(JSON.stringify(await listMapTags(db), null, 2));
      } finally {
        await dispose();
      }
    } else if (command === 'set') {
      const name = flag('name');
      const tag = flag('tag');
      if (!name || !tag) {
        usage();
        process.exit(1);
      }
      const artifactId = Number(flag('artifact')) || undefined;
      const generatorVersion = flag('generator-version');
      const { db, dispose } = await remoteDb();
      try {
        console.log(
          JSON.stringify(
            await tagMap(db, { name, tag, artifactId, generatorVersion }),
            null,
            2,
          ),
        );
      } finally {
        await dispose();
      }
    } else if (command === 'clear') {
      const name = flag('name');
      const tag = flag('tag');
      if (!name || !tag) {
        usage();
        process.exit(1);
      }
      const { db, dispose } = await remoteDb();
      try {
        console.log(JSON.stringify(await clearMapTag(db, name, tag), null, 2));
      } finally {
        await dispose();
      }
    } else {
      usage();
      process.exit(command ? 1 : 0);
    }
  } catch (cause) {
    console.error(cause instanceof Error ? cause.message : String(cause));
    process.exit(1);
  }
}
